### ISSUE TITLE
Better "fe fi fo" function

### ISSUE THREAD

**Issue by connertennery** [clee-dev/Bucket.js#16]
### Problem
When Bucket replies for the "fe fi fo" function, he sometimes gets bad results on the last word in that section. This should instead of operating by syllables (just a guess) should split on the first vowel found.

#### Examples
Currently:
"printables borintables, fe fi fo ftables, printables!"

Desired:
"printables borintables, fe fi fo fintables, printables!"

motion
"motion botion, fe fi fo fotion, motion!"
plenty
"plenty benty, fe fi fo fenty, plenty!"
mukduk
"mukduk bukduk, fe fi fo fukduk, mukduk!"

**Comment by clee-dev** [comment]
Another example of current incorrect behavior:
"everyone boveryone, fe fi fo fyone, everyone!"

**Comment by Tencona** [comment]
More bad behavior. He was triggered on a server emoji.
`:gabegivesup: bo:gabegivesup:558750150571589642>, fe fi fo fabegivesup:558750150571589642>, :gabegivesup:!`

**Comment by clee-dev** [comment]
@Tencona I think that should go in a separate issue, since it's less about how it happens and more about when it happens

**Comment by clee-dev** [comment]
Closed because functionality deprecated
