### ISSUE TITLE
Fix "X is Y"

### ISSUE THREAD

**Issue by clee-dev** [clee-dev/Bucket.js#18]
Me: "@Bucket darling in the franxx is only 15 episodes long
Bucket: "I don't understand"
Me: "@Bucket darling in the franxx \<is\> only 15 episodes long"
Bucket: "Okay"

"is" and "are" factoids are supposed to not require < >

**Comment by Tencona** [comment]
[I think this is why that example for "is" didn't work.](https://github.com/clee-dev/Bucket.js/blob/db47f8ed6894cf2e0bf0032046cf58712393c613/src/main.js#L483)

I'm not sure how of a good way to parse when the user wants to create an "is" factoid.

- "@bucket The Land Before Time XXVII is a movie"
  - "is" is not the second word
- "@bucket Who is the best?"
  - This isn't meant to be trigger, though by learning factoids after looking up factoids, it can be avoided
- "@bucket What is the difference between good and evil?"
  - Probably not trying to set a factoid here, but right now it would trigger learning a new factoid

**Comment by clee-dev** [comment]
@Tencona Interesting. That line is probably a misunderstanding of how the `is` and `are` shorts are supposed to work. According to http://www.xkcdb.com/10685, official behavior is that as long as ` is ` and ` are ` are included in the sentence he's mentioned in, it's regarded as a factoid being taught to him.

**Comment by clee-dev** [comment]
@Tencona 
There's no easy way to determine whether or not you're trying to teach Bucket a shortcut factoid with 'is' and 'are' in the sentence. That'd require some sort of understanding of the sentence, which is not simple code.

The source code does the following regex checks:
```/(.*?)\s+(?:is ?|are ?)(<\w+>)?\s*(.*)()/i
/(.*?)\s+(<\w+(?:'t)?>)\s*(.*)()/i
/(.*?)(<'s>)\s+(.*)()/i
/(.*?)\s+(is(?: also)?|are)\s+(.*)/i```

The last line allows for "is", "are", and "is also" to be shortcut taught

**Comment by Tencona** [comment]
@clee-dev 
Yeah, adding sentience seems a bit out of scope. Maybe that can be revisited later.

The regex could help, but it's just a bit annoying that he'll try to learn a factoid using two super popular words. Ah well.
