### ISSUE TITLE
Bad "fe fi fo" trigger on emoji

### ISSUE THREAD

**Issue by connertennery** [clee-dev/Bucket.js#32]
More bad behavior. He was triggered on a server emoji.
`:gabegivesup: bo:gabegivesup:558750150571589642>, fe fi fo fabegivesup:558750150571589642>, :gabegivesup:!`

_Originally posted by @Tencona in https://github.com/clee-dev/Bucket.js/issues/16#issuecomment-475840039_

**Comment by clee-dev** [comment]
Closed because functionality deprecated
