### ISSUE TITLE
Announce version update in #botspam

### ISSUE THREAD

**Issue by clee-dev** [clee-dev/Bucket.js#39]
Bucket should ping all admins (declared in config file) with a message in #botspam channel on startup that says he restarted. Don't need version numbering or anything, just need to know when he's finally running the new update.
example:
```
@kairos @otheradmin @thirdadmin
I just restarted!
```

eventually channel will be config-able, hopefully by direct conversation with Bucket. for this issue, that's out of scope.

**Comment by malloryleedev** [comment]
Just needs admin pinging

**Comment by connertennery** [comment]
Will the config file need the full Discord account ID for pinging? Haven't worked with the library in a while.

**Comment by clee-dev** [comment]
@connertennery 
```
{
    "channels": {
        "botspam": "000000000000000000" // fake number
    },
    "admins": {
        "username": "000000000000000000" // fake name/number
    },
    "bucketToken": "***",
    "dbUrl": "***"
}
```
